<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use PDO;

/**
 * MessageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function removeOld($amount)
    {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare(
            "DELETE FROM message ORDER BY message.id ASC LIMIT :amount"
        );
        $statement->bindValue('amount', $amount, PDO::PARAM_INT);
        $statement->execute();

        return $statement->rowCount();
    }
}
